package com.redhat.demos.loandemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Credit Score")
   private java.lang.Integer creditScore;
   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;

   public Applicant()
   {
   }

   public java.lang.Integer getCreditScore()
   {
      return this.creditScore;
   }

   public void setCreditScore(java.lang.Integer creditScore)
   {
      this.creditScore = creditScore;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Applicant(java.lang.Integer creditScore, java.lang.String name)
   {
      this.creditScore = creditScore;
      this.name = name;
   }

}