package com.redhat.demos.loandemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Amount")
   private java.lang.Integer amount;
   @org.kie.api.definition.type.Label(value = "Approved")
   private java.lang.Boolean approved;
   @org.kie.api.definition.type.Label(value = "Duration")
   private java.lang.Integer duration;
   @org.kie.api.definition.type.Label(value = "Interest Rate")
   private java.lang.Double interestRate;

   public Loan()
   {
   }

   public java.lang.Integer getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Integer amount)
   {
      this.amount = amount;
   }

   public java.lang.Boolean getApproved()
   {
      return this.approved;
   }

   public void setApproved(java.lang.Boolean approved)
   {
      this.approved = approved;
   }

   public java.lang.Integer getDuration()
   {
      return this.duration;
   }

   public void setDuration(java.lang.Integer duration)
   {
      this.duration = duration;
   }

   public java.lang.Double getInterestRate()
   {
      return this.interestRate;
   }

   public void setInterestRate(java.lang.Double interestRate)
   {
      this.interestRate = interestRate;
   }

   public Loan(java.lang.Integer amount, java.lang.Boolean approved,
         java.lang.Integer duration, java.lang.Double interestRate)
   {
      this.amount = amount;
      this.approved = approved;
      this.duration = duration;
      this.interestRate = interestRate;
   }

}